name: clim-recal
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.08.22
  - libedit=3.1.20221030
  - libev=4.33
  - libgfortran5=11.3.0
  - libssh2=1.10.0
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - pip=23.3
  - python=3.9
  - gdal=3.3.2
  # - r-quarto=1.3
  - readline=8.2
  - setuptools=68.0.0
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - pip:
    - affine==2.3.1
    - attrs==22.1.0
    - backports.strenum==1.2.8
    - certifi==2023.07.22
    - cftime==1.6.2
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - geopandas==0.12.2
    - ipython==8.15.0
    - matplotlib==3.6.1
    - netcdf4==1.6.1
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pillow==9.4.0
    - quartodoc==0.6.3
    - pyparsing==3.0.9
    - pyproj==3.4.0
    - python-dateutil==2.8.2
    - pytest-sugar==0.9.7
    - pytz==2022.5
    - rasterio==1.3.3
    - rioxarray==0.12.3
    - scipy==1.10.0
    - six==1.16.0
    - snuggs==1.4.7
    - tqdm==4.64.1
    - xarray==2023.2.0
