name: clim-recal
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.9.24
  - hdf5=1.12.2
  - krb5=1.19.3
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran5=11.3.0
  - libnghttp2=1.47.0
  - libsqlite=3.39.4
  - libssh2=1.10.0
  - libzlib=1.2.13
  - llvm-openmp=14.0.4
  - ncurses=6.3
  - openssl=3.0.5
  - pip=22.3
  - python=3.11.0
  - readline=8.1.2
  - setuptools=65.5.0
  - tk=8.6.12
  - tzdata=2022e
  - wheel=0.37.1
  - xz=5.2.6
  - geopandas
  - pip:
    - affine==2.3.1
    - attrs==22.1.0
    - certifi==2022.9.24
    - cftime==1.6.2
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - netcdf4==1.6.1
    - numpy==1.23.4
    - packaging==21.3
    - pandas==1.5.1
    - pyparsing==3.0.9
    - pyproj==3.4.0
    - python-dateutil==2.8.2
    - pytz==2022.5
    - rasterio==1.3.3
    - rioxarray==0.12.3
    - six==1.16.0
    - snuggs==1.4.7
    - tqdm==4.64.1
    - xarray==2022.10.0
    - matplotlib==3.6.1
    - scipy==1.10.0
    - pillow==9.4.0
